/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Verify a Thai Citizen Card ID. */
export declare function verifyId(id: string): boolean

/** Alias for verifyId (cross-language consistency) */
export declare function verify_id(id: string): boolean
